// Copyright (C) 2026 Gnana Siva Sai V and Formsmith contributors
// SPDX-License-Identifier: AGPL-3.0-only

import { createAnthropic } from '@ai-sdk/anthropic'
import { createOpenAICompatible } from '@ai-sdk/openai-compatible'
import { generateText, Output } from 'ai'
import type { z } from 'zod'

/**
 * ModelProvider (architecture §5.4) + the hedged-fallback composite
 * (guardrail #7). Providers are instance-level and BYO-key; model tiering
 * (fast/cheap class by default) is the v1 cost story.
 */

export interface GenerateArgs<T> {
  schema: z.ZodType<T>
  system: string
  prompt: string
  /** Distinguishes call shapes for the mock provider (never sent to models). */
  kind: 'followup' | 'form'
  signal?: AbortSignal
}

export interface ModelProvider {
  readonly name: string
  generateStructured<T>(args: GenerateArgs<T>): Promise<T>
}

export const DEFAULT_ANTHROPIC_MODEL = 'claude-haiku-4-5-20251001'

export function createAnthropicProvider(apiKey: string, model?: string): ModelProvider {
  const anthropic = createAnthropic({ apiKey })
  const modelId = model ?? DEFAULT_ANTHROPIC_MODEL
  return {
    name: `anthropic:${modelId}`,
    async generateStructured({ schema, system, prompt, signal }) {
      const result = await generateText({
        model: anthropic(modelId),
        system,
        prompt,
        output: Output.object({ schema }),
        abortSignal: signal,
      })
      return result.output
    },
  }
}

export function createOpenAICompatProvider(
  baseURL: string,
  apiKey: string,
  model: string,
): ModelProvider {
  const client = createOpenAICompatible({ name: 'openai-compatible', baseURL, apiKey })
  return {
    name: `openai-compatible:${model}`,
    async generateStructured({ schema, system, prompt, signal }) {
      const result = await generateText({
        model: client(model),
        system,
        prompt,
        output: Output.object({ schema }),
        abortSignal: signal,
      })
      return result.output
    },
  }
}

/**
 * Deterministic test/dev provider. An answer containing `FAIL_AI` in the
 * prompt makes it throw — how e2e "kills the provider" mid-session.
 */
export function createMockProvider(): ModelProvider {
  let followupCounter = 0
  return {
    name: 'mock',
    async generateStructured<T>({ schema, prompt, kind }: GenerateArgs<T>): Promise<T> {
      if (prompt.includes('FAIL_AI')) throw new Error('mock provider failure (triggered)')
      if (kind === 'form') {
        const title = /about:\s*(.{3,60})/i.exec(prompt)?.[1]?.trim() ?? 'Generated form'
        return schema.parse({
          title,
          blocks: [
            {
              ref: 'welcome',
              type: 'welcome',
              title: `Welcome — ${title}`,
              description: 'Generated by the mock provider.',
            },
            { ref: 'name', type: 'short_text', title: 'What is your name?', required: true },
            {
              ref: 'feedback',
              type: 'long_text',
              title: 'Tell us what you think.',
              required: false,
            },
            { ref: 'thanks', type: 'thankyou', title: 'Thank you!' },
          ],
        })
      }
      followupCounter += 1
      return schema.parse({
        question: `What makes you say that? (mock follow-up ${followupCounter})`,
      })
    },
  }
}

export interface HedgeOptions {
  /** ms before the fallback fires while the primary is still pending. 0 = race. */
  hedgeDelayMs?: number
  /** Hard total budget; both attempts abort past it. */
  timeoutMs?: number
  /** Injectable timers for tests. */
  setTimeoutFn?: typeof setTimeout
  clearTimeoutFn?: typeof clearTimeout
}

/**
 * Hedged fallback (the "tail at scale" pattern): primary fires at t=0; if
 * still pending at hedgeDelay the fallback fires WITHOUT cancelling it —
 * first success wins, the loser is aborted. A HARD primary failure
 * short-circuits the delay. One mechanism, one knob: hedge=0 is racing, no
 * fallback provider is a single chain.
 */
export function withHedgedFallback(
  primary: ModelProvider,
  fallback: ModelProvider | null,
  options: HedgeOptions = {},
): ModelProvider {
  const hedgeDelayMs = options.hedgeDelayMs ?? 3_000
  const timeoutMs = options.timeoutMs ?? 5_000
  const setT = options.setTimeoutFn ?? setTimeout
  const clearT = options.clearTimeoutFn ?? clearTimeout

  if (fallback === null) {
    return {
      name: primary.name,
      async generateStructured(args) {
        const controller = new AbortController()
        const timer = setT(() => controller.abort(), timeoutMs)
        try {
          return await primary.generateStructured({ ...args, signal: controller.signal })
        } finally {
          clearT(timer)
        }
      },
    }
  }

  return {
    name: `${primary.name}+${fallback.name}`,
    async generateStructured<T>(args: GenerateArgs<T>): Promise<T> {
      const primaryController = new AbortController()
      const fallbackController = new AbortController()
      let fallbackStarted = false
      let settled = false

      return new Promise<T>((resolve, reject) => {
        const timers: ReturnType<typeof setT>[] = []
        const finish = (fn: () => void) => {
          if (settled) return
          settled = true
          for (const t of timers) clearT(t)
          primaryController.abort()
          fallbackController.abort()
          fn()
        }

        const startFallback = (primaryError: unknown) => {
          if (fallbackStarted || settled) return
          fallbackStarted = true
          fallback
            .generateStructured({ ...args, signal: fallbackController.signal })
            .then((value) => finish(() => resolve(value)))
            .catch((fallbackError) =>
              finish(() => reject(primaryError instanceof Error ? primaryError : fallbackError)),
            )
        }

        // hard total budget → both die → caller falls back to the static question
        timers.push(
          setT(() => finish(() => reject(new Error('ai generation timed out'))), timeoutMs),
        )
        // the hedge: fallback joins while the primary keeps running
        timers.push(setT(() => startFallback(null), hedgeDelayMs))

        primary
          .generateStructured({ ...args, signal: primaryController.signal })
          .then((value) => finish(() => resolve(value)))
          .catch((error) => {
            // hard failure short-circuits the hedge delay
            if (!fallbackStarted) startFallback(error)
            else if (settled === false && fallbackStarted) {
              /* fallback already running — let it decide the outcome */
            }
          })
      })
    },
  }
}

/** Provider resolution from environment — all optional; nothing set = AI off. */
export function resolveProviders(env: Record<string, string | undefined>): ModelProvider | null {
  const hedge = {
    hedgeDelayMs: Number(env.FORMSMITH_AI_HEDGE_MS ?? 3_000),
    timeoutMs: Number(env.FORMSMITH_AI_TIMEOUT_MS ?? 5_000),
  }

  if (env.FORMSMITH_AI === 'mock') {
    return withHedgedFallback(createMockProvider(), null, hedge)
  }

  const primary =
    env.OPENAI_COMPAT_BASE_URL !== undefined &&
    env.OPENAI_COMPAT_API_KEY !== undefined &&
    env.OPENAI_COMPAT_MODEL !== undefined
      ? createOpenAICompatProvider(
          env.OPENAI_COMPAT_BASE_URL,
          env.OPENAI_COMPAT_API_KEY,
          env.OPENAI_COMPAT_MODEL,
        )
      : env.ANTHROPIC_API_KEY !== undefined
        ? createAnthropicProvider(env.ANTHROPIC_API_KEY, env.FORMSMITH_AI_MODEL)
        : null
  if (primary === null) return null

  const fb = env.FORMSMITH_AI_FALLBACK_PROVIDER
  const fallback =
    fb === 'openai-compatible' &&
    env.FORMSMITH_AI_FALLBACK_BASE_URL !== undefined &&
    env.FORMSMITH_AI_FALLBACK_API_KEY !== undefined &&
    env.FORMSMITH_AI_FALLBACK_MODEL !== undefined
      ? createOpenAICompatProvider(
          env.FORMSMITH_AI_FALLBACK_BASE_URL,
          env.FORMSMITH_AI_FALLBACK_API_KEY,
          env.FORMSMITH_AI_FALLBACK_MODEL,
        )
      : fb === 'anthropic' && env.FORMSMITH_AI_FALLBACK_API_KEY !== undefined
        ? createAnthropicProvider(
            env.FORMSMITH_AI_FALLBACK_API_KEY,
            env.FORMSMITH_AI_FALLBACK_MODEL,
          )
        : null

  return withHedgedFallback(primary, fallback, hedge)
}
